name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Install stuff
        run: |
          apt update
          apt install -y make neovim stylua

      - name: Run tests
        run: make test style-check
